### Успех - 200 OK
GET http://localhost:8088/api/interval-repetition/selected-categories
Content-Type: application/json
X-Telegram-User-Id: 4342423432

### Отсутствует заголовок с user id - 400 Bad Request
GET http://localhost:8088/api/interval-repetition/selected-categories
Content-Type: application/json