### Successful
GET http://localhost:8089//api/interval-repetition/user-auth
Content-Type: application/json
X-Telegram-Username: name
X-Telegram-User-Id: 4342423432
X-User-Roles: ADMIN

### Missing name header -> 403
GET http://localhost:8089//api/interval-repetition/user-auth
Content-Type: application/json
X-Telegram-User-Id: 4342423432
X-User-Roles: ADMIN

### Missing id header -> 403
GET http://localhost:8089//api/interval-repetition/user-auth
Content-Type: application/json
X-Telegram-Username: name
X-User-Roles: ADMIN

### Missing id header -> 403
GET http://localhost:8089//api/interval-repetition/user-auth
Content-Type: application/json
X-Telegram-Username: name
X-Telegram-User-Id: 4342423432

