### 1. Успешный импорт вопроса (200 ok)
POST http://localhost:8088/api/interval-repetition/internal/question
Content-Type: application/json


{
  "specialization": "Java",
  "category": "Java Core",
  "title": "Какие типы ссылок существуют в Java?",
  "answer": "Сильная ссылка..."
}

### 2. Успешная перезапись вопроса (200 ok)
POST http://localhost:8088/api/interval-repetition/internal/question
Content-Type: application/json


{
  "specialization": "Java",
  "category": "Java Core",
  "title": "Какие типы ссылок существуют в Java?",
  "answer": "Другой ответ"
}

### 3. Неуспешный импорт вопроса (400 Bad Request )
# Отсутсвует поле
POST http://localhost:8088/api/interval-repetition/internal/question
Content-Type: application/json


{
  "specialization": "Java",
  "category": "Java Core",
  "title": "Какие типы ссылок существуют в Java?"

}

