spring:
  config:
    activate:
      on-profile: ide

  datasource:
    url: jdbc:postgresql://localhost:5432/it_mentor_community_platform
    username: ${POSTGRES_USERNAME:root}
    password: ${POSTGRES_PASSWORD:password}


server:
  port: 8088